// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqzahuivcydqrslexwar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xemFodWl2Y3lkcXJzbGV4d2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMTE0NjksImV4cCI6MjA1MTY4NzQ2OX0.cMyRCbGUH_HZQuBl7dFpx5TY1pOAho0C0G6PM5nKPSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);